title: Olive & Carambola
url: "https://olivecarambola.github.io/logbook/"
author:
  name: Olive Carambola
  email: olivecarambola@gmail.com

navigation:
  - title: Home
    url: /
  - title: Posts
    url: /posts/
  - title: About
    url: /about/

theme: jekyll-theme-architect

plugins:
  - jekyll-seo-tag
